[package]
name = "tensorlane-client"
version = "0.1.0"
edition = "2024"

[lib]
name = "tensorlane_native"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.104"
sem_safe = { version = "0.2.1", default-features = false, features = ["named"] }
pyo3 = { version = "0.24.0", features = ["anyhow"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postcard = { version = "1", features = ["alloc"] }
futures-util = { version = "0.3", features = ["sink"] }
tokio-util = { version = "0.7", features = ["codec"] }
fs2 = "0.4"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "sync", "time", "net", "io-util", "macros"] }
tonic = "0.13.1"
prost = "0.13.5"
tokio-stream = "0.1.17"

[build-dependencies]
pyo3-build-config = "0.29.2"
protox = "0.7.2"
tonic-build = { version = "0.13.1", default-features = false, features = ["prost"] }

[dev-dependencies]
tokio-stream = { version = "0.1.17", features = ["net"] }
