[package]
name = "tensorlane-client"
version = "0.1.0"
edition = "2024"

[lib]
name = "tensorlane_native"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.104"
pyo3 = { version = "0.24.0", features = ["anyhow"] }
tch = "0.24.0"
pyo3-tch = "0.24.0"
tokio = { version = "1.44.2", features = ["rt", "sync", "time"] }
tonic = "0.13.1"
prost = "0.13.5"
tokio-stream = "0.1.17"

[build-dependencies]
pyo3-build-config = "0.29.2"
protox = "0.7.2"
tonic-build = { version = "0.13.1", default-features = false, features = ["prost"] }

[dev-dependencies]
tokio-stream = { version = "0.1.17", features = ["net"] }
