[project]
name = "tensorlane"
version = "0.1.0"
description = "Client for the TensorLane gRPC service."
requires-python = ">=3.11"
dependencies = [
    "maturin>=1.0,<2.0",
    "torch==2.11.0"
]

[build-system]
requires = ["maturin>=1.0,<2.0","torch==2.11.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "client/Cargo.toml"
python-source = "client"
module-name = "tensorlane._native"

[tool.uv]
no-build-isolation-package = ["tensorlane"]
