from pathlib import Path
from typing import Any

class Daemon:
    def __init__(
        self,
        run_id: str,
        addr: str,
        root: Path,
        ranks: int | None = None,
        prefetch_factor: int | None = None,
        num_workers: int | None = None,
        rank: int = 0,
        api_key: str | None = None,
        timeout: float | None = None,
    ) -> None: ...
    @property
    def run_id(self) -> str: ...
    @property
    def config(self) -> str: ...
    @property
    def assets(self) -> dict[str, Path]: ...
    @property
    def streams(self) -> list[str]: ...
    @property
    def asset_metadata(self) -> dict[str, str]: ...
    @property
    def ranks(self) -> int: ...
    @property
    def num_workers(self) -> int: ...
    @property
    def prefetch_factor(self) -> int: ...
    def close(self) -> None: ...
    def stop(self, error: str | None = None) -> None: ...
    def check(self) -> None: ...
    def ready(self) -> bool: ...

class Listener:
    def __init__(self, path: str | Path) -> None: ...
    def recv(self) -> dict[str, Any] | None: ...

class Semaphore:
    def __init__(self, name: str) -> None: ...
    def post(self) -> None: ...

class UploadClient:
    def __init__(self, path: str | Path, automatic: bool = False) -> None: ...
    def metric(self, step: int, name: str, value: float) -> None: ...
    def metric_artifact(
        self, step: int, path: Path, name: str, content_type: str
    ) -> None: ...
    def save_asset(
        self,
        name: str,
        path: Path,
        step: int = 0,
        kind: str = "file",
        asset_type: str | None = None,
        metadata_json: str = "{}",
        content_type: str = "application/octet-stream",
    ) -> str: ...
    def flush(self, timeout: float | None = None) -> None: ...
    def close(self) -> None: ...
