from pathlib import Path
from typing import Any

class Daemon:
    def __init__(
        self,
        run_id: str,
        addr: str,
        root: Path,
        ranks: int,
        prefetch_factor: int,
        num_workers: int,
    ) -> None: ...
    @property
    def run_id(self) -> str: ...
    @property
    def train_config(self) -> str: ...
    def close(self) -> None: ...
    def stop(self, error: str | None = None) -> None: ...

class Listener:
    def __init__(self, path: str | Path) -> None: ...
    def recv(self) -> dict[str, Any] | None: ...

class Semaphore:
    def __init__(self, name: str) -> None: ...
    def post(self) -> None: ...
