"""Type declarations for the background worker handle."""

from typing import TypeAlias
from torch import Tensor

SampleParts: TypeAlias = tuple[Tensor, float, int, int, Tensor]

class Client:
    def __init__(self, run_id: str, addr: str = "localhost:8181") -> None: ...
    @property
    def run_id(self) -> str: ...
    @property
    def train_config(self) -> str: ...
    def next_batch(self, validation: bool = False) -> list[SampleParts] | None: ...
    def close(self) -> None: ...
